### ISSUE TITLE
code to clean

### ISSUE THREAD

**Issue by iLampard** [wegamekinglc/AlgoTrading#2]
1) \AlgoTrading\Data\DataProviders\DataYes.py
line 112 which should be removed
 
<<<<<<< .working

2)  \AlgoTrading\examples\DataYesBasedStrategy.py
line 54 and line 55 are the same, should remove one line, right?

    Settings.set_source(DataSource.DataYes)
    Settings.set_source(DataSource.DataYes)

**Comment by wegamekinglc** [comment]
let me see see

**Comment by wegamekinglc** [comment]
Thanks for @iLampard for heads up.
